#Default Animal Protect Config Version 1.4.1
notify: true
notify-interval: 10
notify-outdated: false
update-check: false
debug: false
protect-from-player:
     - CHICKEN
     - COW
     - MUSHROOM_COW
     - OCELOT
     - PIG
     - SHEEP
     - WOLF
     - IRON_GOLOM
     - SNOWMAN
protect-from-monsters:
     - VILLAGER