name: AnimalProtect
version: 1.3.2
author: damo1995
main: me.damo1995.AnimalProtect.AnimalProtect
depends: WorldGuard
commands:
   animalprotect:
       description: 'General AnimalProtect Commands'
       usage: /animalprotect /animalprotect -reload
permissions:
  animalprotect.admin:
    description: admin permission node
    children:
      animalprotect.notify: true
      animalprotect.bypass: true
    default: op
  animalprotect.notify:
    description: notify permission node
    default: op
  animalprotect.bypass:
    description: bypass animalprotection.
    default: op